name:                DistrictDeterminer
version:             0.1.0.0
github:              "githubuser/DistrictDeterminer"
license:             BSD3
author:              "Eric Klinkhammer"
maintainer:          "eklinkhammer@pgmail.com"
copyright:           "2021 Eric Klinkhammer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DistrictDeterminer#readme>

dependencies:
- base >= 4.7 && < 5
- hgeometry >= 0.12
- persistent-spatial >= 0.1
- vector >= 0.12
- bytestring >= 0.10.12.0
- cassava >= 0.5.2.0
- turtle >= 1.5.22
- text >= 1.2.4.1
- foldl >= 1.4.12
- hgeometry-combinatorial >= 0.12.0.3

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror

default-extensions:
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - BangPatterns
  - KindSignatures
  - TypeOperators
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeApplications
  - ConstraintKinds
  - RankNTypes
  - DefaultSignatures
  - PatternSynonyms
  - ExistentialQuantification
  - FunctionalDependencies
  - GADTs
  - DataKinds
  - TypeFamilies
  - TypeFamilyDependencies 


executables:
  DistrictDeterminer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DistrictDeterminer

tests:
  DistrictDeterminer-test:
    defaults: hspec/hspec@master
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - DistrictDeterminer
